# Generated by Django 4.2.5 on 2023-11-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("increase", models.PositiveBigIntegerField(default=0)),
                ("decrease", models.PositiveBigIntegerField(default=0)),
                ("total_income", models.PositiveBigIntegerField(default=0)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_incomes",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["staff_id"], name="incomes_dai_staff_i_248341_idx"
                    ),
                    models.Index(fields=["date"], name="incomes_dai_date_d647fe_idx"),
                ],
                "unique_together": {("staff", "date")},
            },
        ),
    ]
